### ISSUE TITLE
ValueError: Input 0 is incompatible with layer model

### ISSUE THREAD

**Issue by ChristianOConnor** [Rohith04MVK/AI-Art-Generator#1]
I ran it with the correct path to both images in the proper variable. It displayed a side my side display of both images and then I was unsure how to proceed because it just hung there. When I closed out of it my terminal printed this error.  
```
(AI-Art-Generator) <myusername>@<mycomputername> AI-Art-Generator % python src/aiart.py 
2021-10-31 <some specific timecode>: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/<myusername>/Desktop/Coding/CodingTestSpace/AI-Art-Generator/src/aiart.py", line 254, in <module>
    best, best_loss = run_style_transfer(content_path, 
  File "/Users/<myusername>/Desktop/Coding/CodingTestSpace/AI-Art-Generator/src/aiart.py", line 177, in run_style_transfer
    style_features, content_features = get_feature_representations(model, content_path, style_path)
  File "/Users/<myusername>/Desktop/Coding/CodingTestSpace/AI-Art-Generator/src/aiart.py", line 117, in get_feature_representations
    style_outputs = model(style_image)
  File "/Users/<myusername>/Desktop/Coding/CodingTestSpace/AI-Art-Generator/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1020, in __call__
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
  File "/Users/<myusername>/Desktop/Coding/CodingTestSpace/AI-Art-Generator/lib/python3.9/site-packages/keras/engine/input_spec.py", line 266, in assert_input_compatibility
    raise ValueError('Input ' + str(input_index) +
ValueError: Input 0 is incompatible with layer model: expected shape=(None, None, None, 3), found shape=(1, 512, 295, 4)
(AI-Art-Generator) <myusername>@<mycomputername> AI-Art-Generator % 
```

**Comment by Rohith04MVK** [comment]
Are both the images of the same extension?

**Comment by ChristianOConnor** [comment]
> Are both the images of the same extension?

Yeah they're both .pngs. Their dimensions are slightly different.

**Comment by Rohith04MVK** [comment]
> Yeah they're both .pngs. Their dimensions are slightly different.

You don't have to worry about the dimensions,but can you convert both of them to jpgs and try?

**Comment by ChristianOConnor** [comment]
Okay that appears to be working! How long does it run for? It's been running for like 10 minutes now

**Comment by Rohith04MVK** [comment]
> Okay that appears to be working! How long does it run for? It's been running for like 10 minutes now

Thats great! It depends on your hardware and the number of iterations. On a GPU (google colab) 1000 iterations took around 5 minutes.

**Comment by Rohith04MVK** [comment]
> Okay that appears to be working! How long does it run for? It's been running for like 10 minutes now

I'll also add a feature so you don't have to manually convert pngs to jpgs. And some kind of indication for the progress 😉

**Comment by ChristianOConnor** [comment]
> > Okay that appears to be working! How long does it run for? It's been running for like 10 minutes now
> 
> Thats great! It depends on your hardware and the number of iterations. On a GPU (google colab) 1000 iterations took around 5 minutes.

Oh awesome thanks for the help great program!

**Comment by ChristianOConnor** [comment]
> > Okay that appears to be working! How long does it run for? It's been running for like 10 minutes now
> 
> I'll also add a feature so you don't have to manually convert pngs to jpgs. And some kind of indication for the progress 😉

Oh nice! Yeah that would be a cool feature thanks! Again great project

**Comment by Rohith04MVK** [comment]
I'll be closing this issue. Have a great life!
