### ISSUE TITLE
Small typo on the readme, the actual file is requirement.txt, not requirements

### ISSUE THREAD

**Issue by KenWuqianghao** [Rohith04MVK/AI-Art-Generator#2]

**Comment by Rohith04MVK** [comment]
Can you specify where?

**Comment by KenWuqianghao** [comment]
![image](https://user-images.githubusercontent.com/20444505/145710440-f128bd5e-3149-424e-8040-03d53d5b62fe.png)

**Comment by Rohith04MVK** [comment]
> ![image](https://user-images.githubusercontent.com/20444505/145710440-f128bd5e-3149-424e-8040-03d53d5b62fe.png)
> 

Iam sorry I didn't see that. I'll be sure to fix it!

**Comment by Rohith04MVK** [comment]
The typo is fixed. Thank you @KenWuqianghao
