### ISSUE TITLE
ModuleNotFoundError: No module named 'tqdm'

### ISSUE THREAD

**Issue by nouaim** [Rohith04MVK/AI-Art-Generator#3]
pip install tqdm

**Comment by Rohith04MVK** [comment]
Is the error in the notebook or the python file?

**Comment by nouaim** [comment]
in the python file, I didn't check the notebook. Just that module should be added to the requirements file

**Comment by Rohith04MVK** [comment]
My bad, I have added it to the requirements. Thanks for your help =)
